export const el = {
  home: document.getElementById("home"),
  scoreboard: document.getElementById("scoreboard"),
  scoreboardList: document.getElementById("scoreboardList"),
  scoreboardNav: document.getElementById("scoreboardNav"),
  breakdown: document.getElementById("breakdown"),
  breakdownCard: document.getElementById("breakdownCard"),
  exitGame: document.getElementById("exitGame"),
  playChrome: document.getElementById("playChrome"),
  playTitle: document.getElementById("playTitle"),
  backHome: document.getElementById("backHome"),
  quizArea: document.getElementById("quizArea"),
  mapArea: document.getElementById("mapArea"),
  studyArea: document.getElementById("studyArea"),
  questionText: document.getElementById("questionText"),
  promptDisplay: document.getElementById("promptDisplay"),
  options: document.getElementById("options"),
  feedback: document.getElementById("feedback"),
  nextBtn: document.getElementById("nextBtn"),
  answerMode: document.getElementById("answerMode"),
  typeWrap: document.getElementById("typeWrap"),
  typeInput: document.getElementById("typeInput"),
  typeSuggest: document.getElementById("typeSuggest"),
  answerStyle: document.querySelectorAll('input[name="answerStyle"]'),
  controls: document.getElementById("controls"),
  filterWrap: document.getElementById("filterWrap"),
  runDock: document.getElementById("runDock"),
  runActions: document.getElementById("runActions"),
  newGame: document.getElementById("newGame"),
  scoreBox: document.getElementById("scoreBox"),
  score: document.getElementById("score"),
  timerStat: document.getElementById("timerStat"),
  timer: document.getElementById("timer"),
  progressStat: document.getElementById("progressStat"),
  progress: document.getElementById("progress"),
  streak: document.getElementById("streak"),
  streakStat: document.getElementById("streakStat"),
  repeatPolicy: document.querySelectorAll('input[name="repeatPolicy"]'),
  filterToggle: document.getElementById("filterToggle"),
  filterPop: document.getElementById("filterPop"),
  filterTree: document.getElementById("filterTree"),
  filterPopTitle: document.getElementById("filterPopTitle"),
  filterAll: document.getElementById("filterAll"),
  filterNone: document.getElementById("filterNone"),
  filterExpand: document.getElementById("filterExpand"),
  filterCollapse: document.getElementById("filterCollapse"),
  mapWrap: document.querySelector(".map-wrap"),
  hudTl: document.getElementById("hudTl"),
  hudTr: document.getElementById("hudTr"),
  hudBr: document.getElementById("hudBr"),
  mapPrompt: document.getElementById("mapPrompt"),
  mapPromptLabel: document.getElementById("mapPromptLabel"),
  mapTargetBlock: document.getElementById("mapTargetBlock"),
  mapTargetFlag: document.getElementById("mapTargetFlag"),
  mapTargetName: document.getElementById("mapTargetName"),
  mapTargetRegion: document.getElementById("mapTargetRegion"),
  mapFeedback: document.getElementById("mapFeedback"),
  mapModeChip: document.getElementById("mapModeChip"),
  toggleExplore: document.getElementById("toggleExplore"),
  newMapTarget: document.getElementById("newMapTarget"),
  settingsWrap: document.getElementById("settingsWrap"),
  settingsBtn: document.getElementById("settingsBtn"),
  settingsBackdrop: document.getElementById("settingsBackdrop"),
  settingsOverlay: document.getElementById("settingsOverlay"),
  settingsPanel: document.querySelector(".settings-panel"),
  settingsClose: document.getElementById("settingsClose"),
  hintContinent: document.getElementById("hintContinent"),
  confirmWrap: document.getElementById("confirmWrap"),
  confirmBackdrop: document.getElementById("confirmBackdrop"),
  confirmPanel: document.querySelector(".confirm-panel"),
  confirmTitle: document.getElementById("confirmTitle"),
  confirmMessage: document.getElementById("confirmMessage"),
  confirmOk: document.getElementById("confirmOk"),
  confirmCancel: document.getElementById("confirmCancel"),
  studyGrid: document.getElementById("studyGrid"),
};

export function tabs() {
  return document.querySelectorAll(".tab");
}

export function gameCards() {
  return document.querySelectorAll(".game-card");
}
